Imports System.Drawing
Imports System.Drawing.Drawing2D
Imports System.Globalization

''' <summary>The website's own icons (lucide line icons and Font Awesome solid icons), drawn from the same SVG
''' shapes, so every icon looks exactly as on the website. The shapes are in IconData.vb (generated by
''' scripts/gen-winforms-icons.mjs from the website's icon packages).</summary>
Public Module Icons
    Private ReadOnly Cache As New Dictionary(Of String, (Path As GraphicsPath, W As Single, H As Single, Fill As Boolean))

    Public Function Has(name As String) As Boolean
        Return IconData.Svg.ContainsKey(name)
    End Function

    ''' <summary>Draws icon <paramref name="name"/> fitted into <paramref name="r"/>. Unknown names draw nothing.</summary>
    Public Sub Draw(g As Graphics, name As String, r As RectangleF, color As Color, Optional strokeWidth As Single = 2)
        Dim ic = Get_(name)
        If ic.Path Is Nothing Then Return
        Dim s = Math.Min(r.Width / ic.W, r.Height / ic.H)
        Dim ox = r.X + (r.Width - ic.W * s) / 2, oy = r.Y + (r.Height - ic.H * s) / 2
        Dim state = g.Save()
        g.SmoothingMode = SmoothingMode.AntiAlias
        g.PixelOffsetMode = PixelOffsetMode.HighQuality
        Using m As New Matrix(s, 0, 0, s, ox, oy)
            Using p = CType(ic.Path.Clone(), GraphicsPath)
                p.Transform(m)
                If ic.Fill Then
                    Using b As New SolidBrush(color) : g.FillPath(b, p) : End Using
                Else
                    ' lucide: stroke 2 on a 24 grid, round ends and joins (at least a hairline when tiny)
                    Using pen As New Pen(color, Math.Max(1.0F, strokeWidth * s)) With {.StartCap = LineCap.Round, .EndCap = LineCap.Round, .LineJoin = LineJoin.Round}
                        g.DrawPath(pen, p)
                    End Using
                End If
            End Using
        End Using
        g.Restore(state)
    End Sub

    Public Sub Draw(g As Graphics, name As String, r As Rectangle, color As Color)
        Draw(g, name, New RectangleF(r.X, r.Y, r.Width, r.Height), color)
    End Sub

    Private Function Get_(name As String) As (Path As GraphicsPath, W As Single, H As Single, Fill As Boolean)
        Dim v As (Path As GraphicsPath, W As Single, H As Single, Fill As Boolean) = Nothing
        If Cache.TryGetValue(name, v) Then Return v
        Dim src As String = Nothing
        If Not IconData.Svg.TryGetValue(name, src) Then Return Nothing
        ' "L|24|24|<element>;<element>…" (L = lucide line icon) or "F|w|h|<path d>" (F = filled, Font Awesome)
        Dim parts = src.Split("|"c, 4)
        Dim fill = parts(0) = "F"
        Dim w = Single.Parse(parts(1), CultureInfo.InvariantCulture), h = Single.Parse(parts(2), CultureInfo.InvariantCulture)
        Dim p As New GraphicsPath(FillMode.Winding)
        If fill Then
            AddPathData(p, parts(3))
        Else
            For Each el In parts(3).Split(";"c)
                If el = "" Then Continue For
                Dim kv = el.Split(":"c, 2)
                Dim n = If(kv.Length > 1, kv(1), "")
                Select Case kv(0)
                    Case "path" : AddPathData(p, n)
                    Case "circle"
                        Dim a = Nums(n)
                        p.StartFigure() : p.AddEllipse(a(0) - a(2), a(1) - a(2), a(2) * 2, a(2) * 2)
                    Case "ellipse"
                        Dim a = Nums(n)
                        p.StartFigure() : p.AddEllipse(a(0) - a(2), a(1) - a(3), a(2) * 2, a(3) * 2)
                    Case "rect"
                        Dim a = Nums(n)
                        p.StartFigure()
                        If a.Count > 4 AndAlso a(4) > 0 Then
                            p.AddPath(Theme_RoundRect(New RectangleF(a(0), a(1), a(2), a(3)), a(4)), False)
                        Else
                            p.AddRectangle(New RectangleF(a(0), a(1), a(2), a(3)))
                        End If
                    Case "line"
                        Dim a = Nums(n)
                        p.StartFigure() : p.AddLine(a(0), a(1), a(2), a(3))
                    Case "polyline", "polygon"
                        Dim a = Nums(n)
                        Dim pts As New List(Of PointF)
                        For k = 0 To a.Count - 2 Step 2 : pts.Add(New PointF(a(k), a(k + 1))) : Next
                        p.StartFigure()
                        If pts.Count > 1 Then p.AddLines(pts.ToArray())
                        If kv(0) = "polygon" Then p.CloseFigure()
                End Select
            Next
        End If
        v = (p, w, h, fill)
        Cache(name) = v
        Return v
    End Function

    ''' <summary>A rounded rectangle with its own radius (icon shapes keep their exact corners).</summary>
    Private Function Theme_RoundRect(r As RectangleF, radius As Single) As GraphicsPath
        Dim p As New GraphicsPath()
        Dim d = Math.Min(radius * 2, Math.Min(r.Width, r.Height))
        p.AddArc(r.X, r.Y, d, d, 180, 90)
        p.AddArc(r.Right - d, r.Y, d, d, 270, 90)
        p.AddArc(r.Right - d, r.Bottom - d, d, d, 0, 90)
        p.AddArc(r.X, r.Bottom - d, d, d, 90, 90)
        p.CloseFigure()
        Return p
    End Function

    Private Function Nums(s As String) As List(Of Single)
        Dim res As New List(Of Single)
        For Each t In Tokens(s)
            If t.IsNum Then res.Add(t.V)
        Next
        Return res
    End Function

    Private Structure Tok
        Public IsNum As Boolean
        Public C As Char
        Public V As Single
    End Structure

    Private Function Tokens(s As String) As List(Of Tok)
        Dim res As New List(Of Tok)
        Dim i = 0
        Dim arc = False, arg = 0 ' inside an arc command: its 4th and 5th numbers are one-digit flags ("a2 2 0 00-2-2")
        While i < s.Length
            Dim c = s(i)
            If Char.IsLetter(c) AndAlso c <> "e"c AndAlso c <> "E"c Then
                res.Add(New Tok With {.C = c}) : i += 1
                arc = c = "A"c OrElse c = "a"c : arg = 0
            ElseIf arc AndAlso (arg Mod 7 = 3 OrElse arg Mod 7 = 4) AndAlso (c = "0"c OrElse c = "1"c) Then
                res.Add(New Tok With {.IsNum = True, .V = If(c = "1"c, 1.0F, 0.0F)}) : i += 1
                arg += 1
            ElseIf Char.IsDigit(c) OrElse c = "-"c OrElse c = "+"c OrElse c = "."c Then
                arg += 1
                Dim st = i
                Dim seenDot = False, seenExp = False
                If c = "-"c OrElse c = "+"c Then i += 1
                While i < s.Length
                    Dim d = s(i)
                    If Char.IsDigit(d) Then
                        i += 1
                    ElseIf d = "."c AndAlso Not seenDot AndAlso Not seenExp Then
                        seenDot = True : i += 1
                    ElseIf (d = "e"c OrElse d = "E"c) AndAlso Not seenExp Then
                        seenExp = True : i += 1
                        If i < s.Length AndAlso (s(i) = "-"c OrElse s(i) = "+"c) Then i += 1
                    Else
                        Exit While
                    End If
                End While
                res.Add(New Tok With {.IsNum = True, .V = Single.Parse(s.Substring(st, i - st), NumberStyles.Float, CultureInfo.InvariantCulture)})
            Else
                i += 1
            End If
        End While
        Return res
    End Function

    ''' <summary>SVG path data (M L H V C S Q T A Z, absolute and relative) into the path.</summary>
    Private Sub AddPathData(p As GraphicsPath, d As String)
        Dim t = Tokens(d)
        Dim i = 0
        Dim cmd As Char = "M"c
        Dim cur As New PointF(0, 0), start As New PointF(0, 0), lastCtrl As New PointF(0, 0)
        Dim lastCmd As Char = " "c
        Dim num = Function() As Single
                      Dim v = t(i).V
                      i += 1
                      Return v
                  End Function
        Dim flag = Function() As Boolean
                       ' arc flags may be written together ("a1 1 0 011 1")
                       Dim v = t(i).V
                       i += 1
                       Return v <> 0
                   End Function
        p.StartFigure()
        While i < t.Count
            If Not t(i).IsNum Then
                cmd = t(i).C : i += 1
                If cmd = "Z"c OrElse cmd = "z"c Then
                    p.CloseFigure() : cur = start : lastCmd = "Z"c
                    Continue While
                End If
                If i >= t.Count OrElse Not t(i).IsNum Then Continue While
            End If
            Dim rel = Char.IsLower(cmd)
            Dim ox = If(rel, cur.X, 0.0F), oy = If(rel, cur.Y, 0.0F)
            Select Case Char.ToUpperInvariant(cmd)
                Case "M"c
                    cur = New PointF(ox + num(), oy + num())
                    start = cur
                    p.StartFigure()
                    cmd = If(rel, "l"c, "L"c)
                    lastCmd = "M"c
                    Continue While
                Case "L"c
                    Dim n As New PointF(ox + num(), oy + num())
                    p.AddLine(cur, n) : cur = n
                Case "H"c
                    Dim n As New PointF(If(rel, cur.X, 0.0F) + num(), cur.Y)
                    p.AddLine(cur, n) : cur = n
                Case "V"c
                    Dim n As New PointF(cur.X, If(rel, cur.Y, 0.0F) + num())
                    p.AddLine(cur, n) : cur = n
                Case "C"c
                    Dim c1 As New PointF(ox + num(), oy + num())
                    Dim c2 As New PointF(ox + num(), oy + num())
                    Dim n As New PointF(ox + num(), oy + num())
                    p.AddBezier(cur, c1, c2, n) : lastCtrl = c2 : cur = n
                Case "S"c
                    Dim c1 = If(Char.ToUpperInvariant(lastCmd) = "C"c OrElse Char.ToUpperInvariant(lastCmd) = "S"c, New PointF(2 * cur.X - lastCtrl.X, 2 * cur.Y - lastCtrl.Y), cur)
                    Dim c2 As New PointF(ox + num(), oy + num())
                    Dim n As New PointF(ox + num(), oy + num())
                    p.AddBezier(cur, c1, c2, n) : lastCtrl = c2 : cur = n
                Case "Q"c
                    Dim q As New PointF(ox + num(), oy + num())
                    Dim n As New PointF(ox + num(), oy + num())
                    AddQuad(p, cur, q, n) : lastCtrl = q : cur = n
                Case "T"c
                    Dim q = If(Char.ToUpperInvariant(lastCmd) = "Q"c OrElse Char.ToUpperInvariant(lastCmd) = "T"c, New PointF(2 * cur.X - lastCtrl.X, 2 * cur.Y - lastCtrl.Y), cur)
                    Dim n As New PointF(ox + num(), oy + num())
                    AddQuad(p, cur, q, n) : lastCtrl = q : cur = n
                Case "A"c
                    Dim rx = num(), ry = num(), rot = num()
                    Dim large = flag(), sweep = flag()
                    Dim n As New PointF(ox + num(), oy + num())
                    AddArc(p, cur, rx, ry, rot, large, sweep, n) : cur = n
                Case Else
                    i += 1
            End Select
            lastCmd = cmd
        End While
    End Sub

    Private Sub AddQuad(p As GraphicsPath, a As PointF, q As PointF, b As PointF)
        Dim c1 As New PointF(a.X + 2.0F / 3 * (q.X - a.X), a.Y + 2.0F / 3 * (q.Y - a.Y))
        Dim c2 As New PointF(b.X + 2.0F / 3 * (q.X - b.X), b.Y + 2.0F / 3 * (q.Y - b.Y))
        p.AddBezier(a, c1, c2, b)
    End Sub

    ''' <summary>SVG elliptical arc (endpoint form) as bezier curves.</summary>
    Private Sub AddArc(p As GraphicsPath, a As PointF, rx As Single, ry As Single, rotDeg As Single, large As Boolean, sweep As Boolean, b As PointF)
        If rx = 0 OrElse ry = 0 Then p.AddLine(a, b) : Return
        rx = Math.Abs(rx) : ry = Math.Abs(ry)
        Dim phi = rotDeg * Math.PI / 180
        Dim cosP = Math.Cos(phi), sinP = Math.Sin(phi)
        Dim dx = (a.X - b.X) / 2.0, dy = (a.Y - b.Y) / 2.0
        Dim x1 = cosP * dx + sinP * dy, y1 = -sinP * dx + cosP * dy
        Dim lam = x1 * x1 / (rx * rx) + y1 * y1 / (ry * ry)
        Dim rxd As Double = rx, ryd As Double = ry
        If lam > 1 Then rxd *= Math.Sqrt(lam) : ryd *= Math.Sqrt(lam)
        Dim num_ = rxd * rxd * ryd * ryd - rxd * rxd * y1 * y1 - ryd * ryd * x1 * x1
        Dim den = rxd * rxd * y1 * y1 + ryd * ryd * x1 * x1
        Dim co = Math.Sqrt(Math.Max(0, num_ / den)) * If(large = sweep, -1, 1)
        Dim cxp = co * rxd * y1 / ryd, cyp = -co * ryd * x1 / rxd
        Dim cx = cosP * cxp - sinP * cyp + (a.X + b.X) / 2.0, cy = sinP * cxp + cosP * cyp + (a.Y + b.Y) / 2.0
        Dim ang = Function(ux As Double, uy As Double, vx As Double, vy As Double) As Double
                      Dim s = If(ux * vy - uy * vx < 0, -1, 1)
                      Dim d = (ux * vx + uy * vy) / (Math.Sqrt(ux * ux + uy * uy) * Math.Sqrt(vx * vx + vy * vy))
                      Return s * Math.Acos(Math.Max(-1, Math.Min(1, d)))
                  End Function
        Dim th1 = ang(1, 0, (x1 - cxp) / rxd, (y1 - cyp) / ryd)
        Dim dth = ang((x1 - cxp) / rxd, (y1 - cyp) / ryd, (-x1 - cxp) / rxd, (-y1 - cyp) / ryd)
        If Not sweep AndAlso dth > 0 Then dth -= 2 * Math.PI
        If sweep AndAlso dth < 0 Then dth += 2 * Math.PI
        Dim segs = CInt(Math.Ceiling(Math.Abs(dth) / (Math.PI / 2)))
        Dim delta = dth / segs
        Dim t = 4.0 / 3 * Math.Tan(delta / 4)
        Dim prev = a
        For k = 0 To segs - 1
            Dim t1 = th1 + k * delta, t2 = t1 + delta
            Dim c1x = Math.Cos(t1) - t * Math.Sin(t1), c1y = Math.Sin(t1) + t * Math.Cos(t1)
            Dim c2x = Math.Cos(t2) + t * Math.Sin(t2), c2y = Math.Sin(t2) - t * Math.Cos(t2)
            Dim ex = Math.Cos(t2), ey = Math.Sin(t2)
            Dim map = Function(x As Double, y As Double) As PointF
                          Dim xx = x * rxd, yy = y * ryd
                          Return New PointF(CSng(cosP * xx - sinP * yy + cx), CSng(sinP * xx + cosP * yy + cy))
                      End Function
            Dim e = If(k = segs - 1, b, map(ex, ey))
            p.AddBezier(prev, map(c1x, c1y), map(c2x, c2y), e)
            prev = e
        Next
    End Sub
End Module
