' GENERATED by scripts/gen-winforms-display-options.mjs from the website's displayOptions files — do not edit.
' Every admin page's "Display Options": the sections (with their parts) and single items a person can hide.
Public Module DisplayDefs
    ''' <summary>Parts hidden until someone turns them on (as on the website).</summary>
    Public ReadOnly DefaultHidden As New Dictionary(Of String, String()) From {
        {"ecom_report_builder_display", {"rb-c-category", "rb-c-gst", "rb-c-status", "rb-c-staff", "rb-p-category", "rb-du-phone", "rb-k-avg", "rb-k-discount", "rb-k-gst"}}}

    Public Function Groups(key As String) As DisplayGroup()
        Select Case key
            Case "activity_logs2_display"
                Return {New DisplayGroup("al2-cards", "Summary Cards", "al2-k-total|Total Events", "al2-k-today|Today", "al2-k-security|Security Events", "al2-k-failed|Failed Actions"),
                    New DisplayGroup("al2-table", "Logs Table", "al2-c-user|User", "al2-c-action|Action", "al2-c-description|Description", "al2-c-tech|Tech Info", "al2-c-severity|Severity", "al2-c-date|Date")}
            Case "ecom_add_product2_display"
                Return {New DisplayGroup("ap2-basic", "Basic Info", "ap2-slug|Slug", "ap2-sku|SKU", "ap2-hsn|HSN Code", "ap2-barcode|Barcode / QR Code", "ap2-desc|Description"),
                    New DisplayGroup("ap2-price", "Pricing & Stock", "ap2-sale|Sale Price", "ap2-stock|Stock Quantity", "ap2-gst|GST Rate", "ap2-qty|Quantity"),
                    New DisplayGroup("ap2-cat", "Categorization", "ap2-category|Category", "ap2-brand|Brand", "ap2-unit|Unit"),
                    New DisplayGroup("ap2-variants", "Variants"),
                    New DisplayGroup("ap2-sizes", "Sizes / Units", "ap2-sz-default|Default size", "ap2-sz-price|Selling Price", "ap2-sz-stock|Stock", "ap2-sz-help|Help text"),
                    New DisplayGroup("ap2-specs", "Specifications", "ap2-sp-help|Help text"),
                    New DisplayGroup("ap2-media", "Product Images", "ap2-image|Featured Image", "ap2-gallery|Gallery"),
                    New DisplayGroup("ap2-org", "Organization", "ap2-status|Status", "ap2-badge|Badge Tag", "ap2-itemtype|Item Type", "ap2-home|Show on Home", "ap2-campaign|Campaign"),
                    New DisplayGroup("ap2-quick", "" & ChrW(&H201C) & "+ Add new" & ChrW(&H201D) & " options", "ap2-q-category|Add new Category", "ap2-q-brand|Add new Brand", "ap2-q-itemtype|Add new Item Type")}
            Case "ecom_analytics2_display"
                Return {New DisplayGroup("a2-cards", "Summary Cards", "a2-k-gross|Gross Sales", "a2-k-net|Net Sales", "a2-k-orders|Orders", "a2-k-aov|Avg Order Value"),
                    New DisplayGroup("a2-widgets", "Widgets", "a2-chart|Revenue & Orders Overview", "a2-payment|Sales by Payment Method", "a2-top|Top Products", "a2-category|Revenue by Category", "a2-insight|Insight card", "a2-customers|New vs Returning Customers")}
            Case "ecom_barcodes2_display"
                Return {New DisplayGroup("bc2-cards", "Key Metrics", "bc2-k-added|Added Today", "bc2-k-updated|Updated Today", "bc2-k-range|In This Range", "bc2-k-queue|Labels to Print", "bc2-k-missing|No Barcode Yet", "bc2-k-total|All Products")}
            Case "ecom_billing2_display"
                Return {New DisplayGroup("b2-cart", "Cart", "b2-col-product|Product", "b2-col-price|Price", "b2-col-qty|Quantity", "b2-col-unit|Unit", "b2-col-subtotal|Subtotal", "b2-col-action|Action"),
                    New DisplayGroup("b2-footer", "Coupon & Totals", "b2-coupon|Coupon Code", "b2-totals|Subtotal / GST / Total"),
                    New DisplayGroup("b2-summary", "Payment Summary", "b2-sum-total|Total Amount", "b2-sum-received|Amount Received", "b2-sum-due|Due / Fully Paid"),
                    New DisplayGroup("b2-checkout", "Customer & Payment", "b2-customer|Customer", "b2-payments|Payment Methods", "b2-secure-note|Secure Payment Note")}
            Case "ecom_brands2_display"
                Return {New DisplayGroup("b2-cards", "Summary Cards", "b2-k-total|Total Brands", "b2-k-enabled|Enabled", "b2-k-popular|Popular", "b2-k-unused|No Products"),
                    New DisplayGroup("b2-filters", "Filters", "b2-f-status|Status", "b2-f-popular|Popular", "b2-f-logo|Logo", "b2-f-products|Products"),
                    New DisplayGroup("b2-table", "Brands Table", "b2-c-select|Select & Bulk Actions", "b2-c-name|Name", "b2-c-logo|Logo", "b2-c-slug|Slug", "b2-c-products|Products", "b2-c-status|Status", "b2-c-popular|Popular", "b2-c-actions|Actions", "b2-t-search|Table Search box")}
            Case "ecom_business_settings_display"
                Return {New DisplayGroup("bs-menu", "Menu Sections", "bs-m-identity|Business Identity", "bs-m-contact|Contact Information", "bs-m-branding|Logo & Branding", "bs-m-social|Social Media", "bs-m-tax|Tax & Legal", "bs-m-invoice|Invoice Settings", "bs-m-pos|POS Shortcuts", "bs-m-orders|Barcode & Orders", "bs-m-payment|Payment Methods", "bs-m-gst|GST / Tax Rates", "bs-m-login|Login & OTP"),
                    New DisplayGroup("bs-preview", "Live Preview", "bs-p-device|Mobile / Desktop switch", "bs-p-audience|Guest / Logged-in switch")}
            Case "cache_manager2_display"
                Return {New DisplayGroup("cm2-cards", "Summary Cards", "cm2-k-size|Cache Size", "cm2-k-total|Total Clears", "cm2-k-last|Last Cleared"),
                    New DisplayGroup("cm2-redis", "Redis Cache panel", "cm2-redis-panel|Redis status & flush"),
                    New DisplayGroup("cm2-sections", "Cache Sections", "cm2-sections-list|Section cards"),
                    New DisplayGroup("cm2-history", "Clear History panel", "cm2-history-panel|Clear History")}
            Case "ecom_campaign_offer2_display"
                Return {New DisplayGroup("co2-metrics", "Key Metrics", "co2-m-live|Active Campaigns", "co2-m-products|Products on Offer", "co2-m-sales|Campaign Sales", "co2-m-units|Units Sold", "co2-m-discount|Discount Given", "co2-m-orders|Orders with Offer"),
                    New DisplayGroup("co2-campaigns", "Campaigns & History", "co2-c-applies|Applies To", "co2-c-offer|Offer", "co2-c-schedule|Schedule", "co2-c-status|Status", "co2-c-sales|Sales", "co2-c-actions|Actions", "co2-c-search|Search box"),
                    New DisplayGroup("co2-offers", "Products on Offer", "co2-p-image|Image", "co2-p-price|Price", "co2-p-campaign|Campaign", "co2-p-ends|Ends", "co2-p-actions|Actions", "co2-p-search|Search box")}
            Case "ecom_categories2_display"
                Return {New DisplayGroup("c2-cards", "Summary Cards", "c2-k-total|Total Categories", "c2-k-active|Active Categories", "c2-k-inactive|Inactive Categories", "c2-k-products|Products Assigned"),
                    New DisplayGroup("c2-filters", "Filters", "c2-f-status|Status", "c2-f-sort|Sort"),
                    New DisplayGroup("c2-table", "Categories Table", "c2-c-select|Select & Bulk Actions", "c2-c-image|Image", "c2-c-name|Category Name", "c2-c-slug|Slug", "c2-c-products|Products", "c2-c-serial|Serial", "c2-c-status|Status", "c2-c-updated|Last Updated", "c2-c-actions|Actions", "c2-t-search|Table Search box")}
            Case "ecom_coupons2_display"
                Return {New DisplayGroup("cp2-cards", "Summary Cards", "cp2-k-active|Active Coupons", "cp2-k-scheduled|Scheduled Coupons", "cp2-k-expired|Expired Coupons", "cp2-k-redemptions|Total Redemptions"),
                    New DisplayGroup("cp2-grid", "Coupon Grid", "cp2-search|Search & filters"),
                    New DisplayGroup("cp2-activity", "Recent Activity panel", "cp2-activity-panel|Recent Activity")}
            Case "ecom_customers2_display"
                Return {New DisplayGroup("cus2-cards", "Key Metrics", "cus2-k-total|All Customers", "cus2-k-online|Online Customers", "cus2-k-offline|Store Customers", "cus2-k-dues|With Dues"),
                    New DisplayGroup("cus2-filters", "Filters", "cus2-f-type|Customer Type", "cus2-f-status|Status", "cus2-f-dues|Dues", "cus2-f-activity|Buying", "cus2-f-datefield|Date applies to"),
                    New DisplayGroup("cus2-table", "Customer Table", "cus2-c-customer|Customer", "cus2-c-photo|Profile photo", "cus2-c-joined|Joined / last order line", "cus2-c-contact|Contact", "cus2-c-type|Type", "cus2-c-orders|Orders", "cus2-c-spent|Total Spent", "cus2-c-due|Due", "cus2-c-login|Login (OTP / password)", "cus2-c-addresses|Saved addresses", "cus2-c-status|Status", "cus2-c-actions|Actions", "cus2-t-search|Search box")}
            Case "ecom_customer_profile_display"
                Return {New DisplayGroup("cp-header", "Profile Header", "cp-h-contact|Phone, email & since", "cp-h-login|Login methods", "cp-h-actions|Edit / New order buttons", "cp-h-call|Call / WhatsApp buttons"),
                    New DisplayGroup("cp-stats", "Numbers", "cp-k-orders|Orders", "cp-k-spent|Total spent", "cp-k-avg|Average order", "cp-k-due|Due", "cp-k-last|Last order"),
                    New DisplayGroup("cp-tabs", "Tabs", "cp-t-orders|Orders", "cp-t-addresses|Addresses", "cp-t-due|Due history"),
                    New DisplayGroup("cp-cols", "Orders Table", "cp-c-order|Order", "cp-c-date|Date", "cp-c-total|Total", "cp-c-payment|Payment", "cp-c-status|Status", "cp-c-view|Open button")}
            Case "ecom_dashboard2_widgets"
                Return {New DisplayGroup("d2-orders", "Orders & Customers", "d2-on-total|Total Orders", "d2-on-pending|Pending Orders", "d2-on-progress|In Progress", "d2-on-delivered|Delivered Orders", "d2-on-canceled|Canceled Orders", "d2-cust-online|Total Online Customers", "d2-cust-offline|Total Offline Customers", "d2-sold-store|Today Store Sold Product", "d2-sold-online|Today Online Sold Product"),
                    New DisplayGroup("d2-earnings", "Earnings & Due", "d2-earning|Earnings", "d2-due|Due", "d2-received|Payment Received", "d2-pending-pay|Pending Payment"),
                    New DisplayGroup("d2-overview", "Store Overview", "d2-products|Products", "d2-categories|Categories", "d2-brands|Brands", "d2-coupons|Active Coupons")}
            Case "ecom_deliveries_display"
                Return {New DisplayGroup("dv-stats", "Numbers", "dv-k-waiting|Waiting for an agent", "dv-k-onway|On the way", "dv-k-delivered|Delivered today", "dv-k-collect|Cash to collect", "dv-k-cash|Cash collected today", "dv-k-agents|Agents busy / free"),
                    New DisplayGroup("dv-waiting", "Waiting for an Agent", "dv-w-customer|Customer", "dv-w-amount|Amount", "dv-w-payment|Paid / to collect", "dv-w-address|Address", "dv-w-items|Items", "dv-w-contact|Call / map buttons", "dv-w-assign|Assign box"),
                    New DisplayGroup("dv-agents", "Agent Cards", "dv-a-summary|Active / delivered line", "dv-a-collect|To collect", "dv-a-cash|Cash today", "dv-a-orders|Order list", "dv-a-customer|Customer & amount line", "dv-a-time|Assigned how long ago", "dv-a-status|On the way / to pick up tag")}
            Case "ecom_due2_display"
                Return {New DisplayGroup("due2-cards", "Summary Cards", "due2-k-total|Total Due", "due2-k-overdue|Overdue", "due2-k-today|Due Today", "due2-k-people|People with Dues"),
                    New DisplayGroup("due2-filters", "Filters", "due2-f-status|Status", "due2-f-promise|Promise Date", "due2-f-source|Order Source", "due2-f-product|Product", "due2-f-datefield|Date applies to"),
                    New DisplayGroup("due2-table", "Due Table", "due2-c-select|Select & Bulk Collect", "due2-c-customer|Customer", "due2-c-order|Order", "due2-c-amount|Amount & Paid", "due2-c-balance|Balance", "due2-c-promise|Promise Date", "due2-c-status|Status", "due2-c-actions|Actions", "due2-t-search|Search box")}
            Case "file_manager2_display"
                Return {New DisplayGroup("fm2-cards", "Summary Cards", "fm2-k-total|Total Files", "fm2-k-images|Images", "fm2-k-pdfs|PDFs", "fm2-k-assets|Site Assets"),
                    New DisplayGroup("fm2-upload", "Upload zone", "fm2-upload-zone|Drag & drop upload area"),
                    New DisplayGroup("fm2-toolbar", "Search & filters", "fm2-f-search|Search box", "fm2-f-type|Type filter", "fm2-f-category|Category filter", "fm2-f-sort|Sort")}
            Case "ecom_login_settings_display"
                Return {New DisplayGroup("ls-sections", "Sections", "ls-status|Status banner", "ls-options|Login options", "ls-firebase|Firebase web config", "ls-steps|Firebase setup steps"),
                    New DisplayGroup("ls-preview", "Live Preview", "ls-p-device|Mobile / Desktop switch", "ls-p-audience|Guest / Logged-in switch")}
            Case "ecom_order_view_display"
                Return {New DisplayGroup("ov-header", "Order Header", "ov-h-date|Date & time", "ov-h-type|Online / store bill", "ov-h-total|Order total", "ov-h-pills|Status & payment pills", "ov-h-print|Print buttons (A4 / Thermal)", "ov-h-contact|Call / WhatsApp buttons"),
                    New DisplayGroup("ov-items", "Items Table", "ov-c-num|#", "ov-c-image|Product photo", "ov-c-product|Product", "ov-c-qty|Quantity", "ov-c-price|Price", "ov-c-gst|GST %", "ov-c-subtotal|Amount", "ov-c-remove|Remove button", "ov-i-add|Add a product"),
                    New DisplayGroup("ov-bill", "Bill Summary", "ov-b-subtotal|Subtotal", "ov-b-discount|Discount", "ov-b-gst|GST", "ov-b-paid|Paid", "ov-b-due|Due"),
                    New DisplayGroup("ov-side", "Right Side Cards", "ov-s-actions|Actions (accept, agent, payment…)", "ov-s-customer|Customer", "ov-s-address|Delivery address", "ov-s-map|Map of the delivery spot", "ov-s-payment|Payment details")}
            Case "ecom_orders2_display"
                Return {New DisplayGroup("or2-cards", "Summary Cards", "or2-k-total|Orders in view", "or2-k-today|Today's Orders", "or2-k-unpaid|Unpaid", "or2-k-value|Order Value", "or2-k-pending|Pending", "or2-k-in-progress|In Progress", "or2-k-out-for-delivery|Out for Delivery", "or2-k-delivered|Delivered"),
                    New DisplayGroup("or2-filters", "Filters", "or2-f-payment|Payment", "or2-f-method|Payment Method", "or2-f-product|Product", "or2-f-dues|Balance", "or2-f-agent|Delivery agent"),
                    New DisplayGroup("or2-table", "Order Table", "or2-c-select|Tick boxes (bulk actions)", "or2-c-order|Order", "or2-c-customer|Customer", "or2-c-items|Items", "or2-c-total|Total", "or2-c-payment|Payment", "or2-c-status|Status", "or2-c-agent|Delivery agent", "or2-c-contact|Call / WhatsApp / map buttons", "or2-c-actions|Actions", "or2-t-search|Search box", "or2-t-pagesize|Orders per page"),
                    New DisplayGroup("or2-details", "Row Details", "or2-d-date|Order date & time", "or2-d-phone|Customer phone / email", "or2-d-itemname|First item name", "or2-d-method|Payment method", "or2-d-due|Amount still due", "or2-d-decide|Accept / Reject buttons", "or2-d-agentline|Agent name under status", "or2-d-highlight|Highlight new orders", "or2-d-compact|Compact rows")}
            Case "ecom_pages_display"
                Return {New DisplayGroup("pg-stats", "Numbers", "pg-k-total|All pages", "pg-k-published|Published", "pg-k-draft|Drafts"),
                    New DisplayGroup("pg-table", "Pages Table", "pg-t-search|Search box", "pg-t-tabs|All / Published / Draft tabs", "pg-c-title|Title", "pg-c-slug|Link (slug)", "pg-c-status|Status", "pg-c-updated|Last updated", "pg-c-actions|Actions")}
            Case "ecom_page_editor_display"
                Return {New DisplayGroup("pe-form", "Form", "pe-slug|Slug", "pe-status|Status", "pe-seo|SEO (meta title & description)"),
                    New DisplayGroup("pe-preview", "Live Preview", "pe-p-device|Mobile / Desktop switch", "pe-p-audience|Guest / Logged-in switch")}
            Case "ecom_my_profile_display"
                Return {New DisplayGroup("mp-sections", "Sections", "mp-card|Photo & role card", "mp-details|Personal details", "mp-password|Change password")}
            Case "ecom_customizer_display"
                Return {New DisplayGroup("cz-tabs", "Section Tabs", "cz-t-icons|Icons", "cz-t-hints|Short descriptions"),
                    New DisplayGroup("cz-toolbar", "Preview Toolbar", "cz-b-status|Save / publish status", "cz-b-device|Mobile / Desktop switch", "cz-b-reload|Reload preview button", "cz-b-open|Open in new tab button", "cz-b-audience|Guest / Logged-in switch (header & footer)")}
            Case "ecom_payment_settings2_display"
                Return {New DisplayGroup("pm2-cards", "Summary Cards", "pm2-k-enabled|Enabled Methods", "pm2-k-configured|Configured Methods", "pm2-k-default|Default Method"),
                    New DisplayGroup("pm2-default", "Default Payment Method panel", "pm2-default-panel|Default Payment Method")}
            Case "ecom_product_tags2_display"
                Return {New DisplayGroup("tg2-cards", "Summary Cards", "tg2-k-badges|Badge Tags", "tg2-k-types|Item Types", "tg2-k-active|Active", "tg2-k-unused|Not Used", "tg2-k-tagged|Tagged Products", "tg2-k-units|Units Sold", "tg2-k-revenue|Sales from Badges", "tg2-k-top|Best Performing"),
                    New DisplayGroup("tg2-filters", "Filters", "tg2-f-group|Tag Type", "tg2-f-status|Status", "tg2-f-usage|Usage"),
                    New DisplayGroup("tg2-table", "Tag Table", "tg2-c-tag|Tag", "tg2-c-group|Type", "tg2-c-products|Products", "tg2-c-sales|Units Sold", "tg2-c-revenue|Sales", "tg2-c-status|Status", "tg2-c-actions|Actions", "tg2-t-search|Search box")}
            Case "ecom_products2_display"
                Return {New DisplayGroup("p2-cards", "Summary Cards", "p2-k-total|Total Products", "p2-k-published|Published", "p2-k-low|Low Stock", "p2-k-out|Out of Stock"),
                    New DisplayGroup("p2-filters", "Filters", "p2-f-status|Status", "p2-f-stock|Stock", "p2-f-category|Category", "p2-f-type|Type", "p2-f-item|Item Type"),
                    New DisplayGroup("p2-table", "Products Table", "p2-c-select|Select & Bulk Actions", "p2-c-image|Image", "p2-c-name|Name", "p2-c-stock|Stock", "p2-c-category|Category", "p2-c-price|Price", "p2-c-status|Status", "p2-c-type|Type", "p2-c-item|Item Type", "p2-c-actions|Actions")}
            Case "push_manager2_display"
                Return {New DisplayGroup("pm2-header", "Header buttons", "pm2-b-export|Export", "pm2-b-import|Import", "pm2-b-new|New Push"),
                    New DisplayGroup("pm2-cards", "Summary Cards", "pm2-k-subs|Subscribers", "pm2-k-campaigns|Campaigns", "pm2-k-sent|Delivered", "pm2-k-failed|Failed", "pm2-k-rate|Delivery Rate"),
                    New DisplayGroup("pm2-types", "Promote options", "pm2-t-product|Product", "pm2-t-category|Category", "pm2-t-brand|Brand", "pm2-t-offer|Offer / Coupon", "pm2-t-custom|Custom URL"),
                    New DisplayGroup("pm2-compose", "Compose", "pm2-c-target|What to promote", "pm2-c-templates|Message templates", "pm2-c-fields|Notification details", "pm2-c-counters|Character counters", "pm2-c-utm|UTM tracking", "pm2-c-actions|Send buttons", "pm2-c-preview|Lock screen preview", "pm2-c-note|Preview note"),
                    New DisplayGroup("pm2-history", "History", "pm2-h-live|Live status line", "pm2-h-image|Thumbnail", "pm2-h-status|Status", "pm2-h-progress|Progress", "pm2-h-counts|Sent / Failed", "pm2-h-total|Total", "pm2-h-time|Time", "pm2-h-actions|Actions", "pm2-h-pager|Pagination"),
                    New DisplayGroup("pm2-subs", "Subscribers", "pm2-s-breakdown|Browser breakdown", "pm2-s-tools|Import / Export", "pm2-s-table|Subscriber list", "pm2-s-pager|Pagination"),
                    New DisplayGroup("pm2-settings", "Settings", "pm2-st-form|VAPID keys form", "pm2-st-status|Key tools (generate / backup)", "pm2-st-help|Where to get keys guide")}
            Case "ecom_report_builder_display"
                Return {New DisplayGroup("rb-filters", "Filters", "rb-f-presets|Today / Yesterday / This & Previous Month", "rb-f-month|Month picker (January, February…)", "rb-f-range|Date range & Custom Range", "rb-f-channel|All Sales / In-store / Online", "rb-f-staff|Staff (report for one person)"),
                    New DisplayGroup("rb-head", "Report Header", "rb-h-logo|Logo", "rb-h-name|Business name & tagline", "rb-h-address|Address", "rb-h-contact|Mobile & email", "rb-h-gstin|GSTIN", "rb-h-generated|Generated on"),
                    New DisplayGroup("rb-kpi", "Summary Cards", "rb-k-sales|Total Sales", "rb-k-units|Total Products Sold", "rb-k-due|Total Dues", "rb-k-collected|Due Collected", "rb-k-added|Products Added", "rb-k-newdue|New Dues", "rb-k-avg|Average Order", "rb-k-discount|Discount Given", "rb-k-gst|GST Collected", "rb-k-online|Online Orders Placed"),
                    New DisplayGroup("rb-tl", "Product-wise Sales Timeline", "rb-c-time|Time", "rb-c-order|Order ID", "rb-c-channel|Channel", "rb-c-customer|Customer", "rb-c-phone|Customer mobile", "rb-c-product|Product", "rb-c-sku|SKU", "rb-c-category|Category", "rb-c-qty|Qty", "rb-c-price|Unit Price", "rb-c-total|Total", "rb-c-gst|GST", "rb-c-payment|Payment", "rb-c-due|Due", "rb-c-status|Order status", "rb-c-staff|Sold / delivered by"),
                    New DisplayGroup("rb-g-products", "Product Summary", "rb-p-name|Product", "rb-p-sku|SKU", "rb-p-category|Category", "rb-p-orders|Orders", "rb-p-qty|Qty sold", "rb-p-revenue|Revenue", "rb-p-last|Last sold"),
                    New DisplayGroup("rb-g-daily", "Day-wise Summary", "rb-d-day|Date", "rb-d-orders|Orders", "rb-d-offline|In-store", "rb-d-online|Online", "rb-d-units|Units", "rb-d-sales|Sales", "rb-d-due|Due", "rb-d-collected|Collected"),
                    New DisplayGroup("rb-g-collections", "Due Collections", "rb-col-time|Time", "rb-col-receipt|Receipt", "rb-col-customer|Customer", "rb-col-order|Order", "rb-col-method|Method", "rb-col-amount|Amount", "rb-col-by|Received by"),
                    New DisplayGroup("rb-g-dues", "New Dues", "rb-du-time|Time", "rb-du-order|Order", "rb-du-customer|Customer", "rb-du-phone|Mobile", "rb-du-amount|Due amount", "rb-du-paid|Paid since", "rb-du-balance|Balance", "rb-du-promised|Promised date", "rb-du-status|Status"),
                    New DisplayGroup("rb-g-added", "Products Added", "rb-a-time|Time", "rb-a-name|Product", "rb-a-sku|SKU", "rb-a-category|Category", "rb-a-price|Price", "rb-a-stock|Stock", "rb-a-by|Added by"),
                    New DisplayGroup("rb-g-agents", "Deliveries by Agent", "rb-ag-name|Agent", "rb-ag-assigned|Assigned", "rb-ag-delivered|Delivered", "rb-ag-pending|Pending", "rb-ag-canceled|Canceled", "rb-ag-value|Delivered value", "rb-ag-avg|Avg. delivery time"),
                    New DisplayGroup("rb-g-staff", "Staff Performance", "rb-st-name|Staff", "rb-st-role|Role", "rb-st-pos|Store sales", "rb-st-posamt|Store sales amount", "rb-st-col|Collections", "rb-st-colamt|Collected amount", "rb-st-delivered|Delivered", "rb-st-added|Products added"),
                    New DisplayGroup("rb-g-activity", "Staff Activity (one person)", "rb-ac-time|Time", "rb-ac-action|Action", "rb-ac-details|Details"),
                    New DisplayGroup("rb-side", "Right Panel", "rb-r-payment|Payment Summary", "rb-r-channel|Sales Channel Summary", "rb-r-online|Online Orders by Status", "rb-r-aging|Due Aging Summary", "rb-r-export|Export Report")}
            Case "ecom_reviews2_display"
                Return {New DisplayGroup("rv2-cards", "Summary Cards", "rv2-k-total|All Reviews", "rv2-k-today|Today", "rv2-k-pending|Pending Reviews", "rv2-k-approved|Approved", "rv2-k-rejected|Rejected", "rv2-k-average|Average Rating", "rv2-k-low|Low Ratings", "rv2-k-range|In Selected Range"),
                    New DisplayGroup("rv2-filters", "Filters", "rv2-f-status|Status", "rv2-f-rating|Rating", "rv2-f-category|Category", "rv2-f-product|Product", "rv2-f-text|Message"),
                    New DisplayGroup("rv2-table", "Review Table", "rv2-c-product|Product", "rv2-c-customer|Name", "rv2-c-rating|Rating", "rv2-c-review|Review", "rv2-c-status|Status", "rv2-c-actions|Actions", "rv2-t-search|Search box")}
            Case "ecom_sales_history2_display"
                Return {New DisplayGroup("sh2-metrics", "Key Metrics", "sh2-m-total|Total Sales", "sh2-m-today|Today's Sale", "sh2-m-yesterday|Yesterday's Sale", "sh2-m-week|This Week's Sale", "sh2-m-month|This Month's Sale", "sh2-m-due|Today's Due Collection"),
                    New DisplayGroup("sh2-ledger", "Sales Ledger", "sh2-c-time|Time", "sh2-c-order|Order ID", "sh2-c-customer|Customer", "sh2-c-items|Items", "sh2-c-payment|Payment", "sh2-c-total|Total", "sh2-c-paid|Paid", "sh2-c-invoice|Invoice")}
            Case "ecom_stock_out2_display"
                Return {New DisplayGroup("so2-cards", "Summary Cards", "so2-k-total|Out of Stock", "so2-k-active|Active (Live in Shop)", "so2-k-inactive|Inactive", "so2-k-units|With Units"),
                    New DisplayGroup("so2-filters", "Filters", "so2-f-status|Status", "so2-f-category|Category", "so2-f-units|Units", "so2-f-stock|Stock"),
                    New DisplayGroup("so2-table", "Stock Out Table", "so2-c-select|Select & Bulk Actions", "so2-c-image|Image", "so2-c-name|Name", "so2-c-category|Category", "so2-c-price|Price", "so2-c-status|Status", "so2-c-stock|Stock", "so2-c-actions|Actions", "so2-t-search|Table Search box")}
            Case "ecom_tax_settings2_display"
                Return {New DisplayGroup("tx2-cards", "Summary Cards", "tx2-k-total|Total Slabs", "tx2-k-default|Default Rate", "tx2-k-highest|Highest Rate", "tx2-k-orphan|Products Without a Matching Slab"),
                    New DisplayGroup("tx2-table", "GST Slabs Table", "tx2-c-label|Label", "tx2-c-rate|Rate", "tx2-c-products|Products", "tx2-c-default|Default", "tx2-c-actions|Actions", "tx2-t-search|Table Search box")}
            Case "user_manager2_display"
                Return {New DisplayGroup("u2-cards", "Summary Cards", "u2-k-total|Total Users", "u2-k-admins|Admins", "u2-k-active|Active", "u2-k-suspended|Suspended / Pending"),
                    New DisplayGroup("u2-table", "Users Table", "u2-c-user|User", "u2-c-role|Role", "u2-c-status|Status", "u2-c-permissions|Permissions summary", "u2-c-actions|Actions", "u2-t-search|Table Search box")}
            Case "app_gst_display"
                Return {New DisplayGroup("gst-filters", "Filters", "gst-f-period|Period buttons", "gst-f-channel|All / Store / Online", "gst-f-dates|Date line"),
                    New DisplayGroup("gst-cards", "Summary Cards", "gst-k-invoices|Invoices", "gst-k-taxable|Taxable value", "gst-k-gst|Total GST", "gst-k-value|Invoice value"),
                    New DisplayGroup("gst-tabs", "Report tabs", "gst-t-rate|Rate-wise", "gst-t-hsn|HSN-wise", "gst-t-product|Product-wise", "gst-t-invoice|Invoice-wise")}
            Case "app_backup_display"
                Return {New DisplayGroup("bk-table", "Backups Table", "bk-c-size|Size", "bk-c-made|Made", "bk-c-actions|Actions")}
            Case "app_staffapp_display"
                Return {}
            Case Else : Return {}
        End Select
    End Function

    Public Function Singles(key As String) As String()
        Select Case key
            Case "ecom_barcodes2_display" : Return {"bc2-range|Date Range Bar", "bc2-preview|Label Preview", "bc2-picker|Add Products box", "bc2-list|Print List"}
            Case "ecom_billing2_display" : Return {"b2-scan|Scan / Search Bar", "b2-add-product|Add Product Button"}
            Case "ecom_business_settings_display" : Return {"bs-savenote|Note beside the Save button"}
            Case "ecom_campaign_offer2_display" : Return {"co2-range|Date Range Bar", "co2-chart|Campaign Sales Graph"}
            Case "ecom_customers2_display" : Return {"cus2-chart|Customer Growth graph", "cus2-range|Date Range Bar"}
            Case "ecom_customer_profile_display" : Return {"cp-address|Address on file"}
            Case "ecom_dashboard2_widgets" : Return {"d2-recent|Recent Orders", "d2-sales|Sales Overview"}
            Case "ecom_due2_display" : Return {"due2-range|Date Range Bar"}
            Case "ecom_order_view_display" : Return {"ov-progress|Progress bar (Placed → Delivered)", "ov-history|Order history"}
            Case "ecom_orders2_display" : Return {"or2-range|Date range", "or2-tabs|Status tabs", "or2-bulk|Bulk actions bar (when orders are ticked)", "or2-summary|Summary line (count & value shown)", "or2-pager|Page numbers"}
            Case "ecom_customizer_display" : Return {"cz-draft-note|" & ChrW(&H201C) & "Edits save as a draft" & ChrW(&H201D) & " note"}
            Case "ecom_product_tags2_display" : Return {"tg2-range|Date Range Bar", "tg2-orphans|Untagged values notice"}
            Case "push_manager2_display" : Return {"pm2-notice|Setup warning (only when keys are missing)"}
            Case "ecom_reviews2_display" : Return {"rv2-range|Date Range Bar", "rv2-spread|Ratings Breakdown"}
            Case "ecom_sales_history2_display" : Return {"sh2-chart|Sales Performance", "sh2-filters|Filter Sales"}
            Case "app_backup_display" : Return {"bk-progress|Progress card", "bk-note|Upload / download note"}
            Case "app_staffapp_display" : Return {"sa-version|This device", "sa-install|Install on another device"}
            Case Else : Return {}
        End Select
    End Function
End Module
